### ISSUE TITLE
Version 1.4.4 still build problems

### ISSUE THREAD

**Issue by taar1** [HITGIF/TextFieldBoxes#105]
Just upgraded from version 1.3.4 to version 1.4.4 in the hopes that the build will run through now. However, I still can't compile it with version 1.4.4. Version 1.3.4 is the highest version that works for me. Anything from 1.3.5 up to version 1.4.4 is not working. 

Here is the error I get:

> /Users/dominikerbsland/workspace/app/Android/other/Gaze/app/build/intermediates/incremental/mergeGooglePlayFlavorDebugResources/merged.dir/values/values.xml: error: file failed to compile.
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.android.ide.common.workers.ExecutorServiceAdapter.await(ExecutorServiceAdapter.kt:56)
	... 87 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/Users/dominikerbsland/.gradle/caches/transforms-2/files-2.1/bac46a2a7f14666195dd82648a1252d5/res/values/values.xml:1167:5-1182:23: AAPT: error: duplicate value for resource 'attr/counterTextColor' with config ''.
    
> /Users/dominikerbsland/.gradle/caches/transforms-2/files-2.1/bac46a2a7f14666195dd82648a1252d5/res/values/values.xml:1167:5-1182:23: AAPT: error: resource previously defined here.
    
> /Users/dominikerbsland/workspace/app/Android/other/Gaze/app/build/intermediates/incremental/mergeGooglePlayFlavorDebugResources/merged.dir/values/values.xml: error: file failed to compile.
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteCompileException(Aapt2ErrorUtils.kt:55)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:39)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:28)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon(Aapt2DaemonManagerService.kt:71)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon$default(Aapt2DaemonManagerService.kt:69)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable.run(Aapt2CompileWithBlameRunnable.kt:34)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:40)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/Users/dominikerbsland/workspace/app/Android/other/Gaze/app/build/intermediates/incremental/mergeGooglePlayFlavorDebugResources/merged.dir/values/values.xml:9042: error: duplicate value for resource 'attr/counterTextColor' with config ''.
/Users/dominikerbsland/workspace/app/Android/other/Gaze/app/build/intermediates/incremental/mergeGooglePlayFlavorDebugResources/merged.dir/values/values.xml:9042: error: resource previously defined here.
/Users/dominikerbsland/workspace/app/Android/other/Gaze/app/build/intermediates/incremental/mergeGooglePlayFlavorDebugResources/merged.dir/values/values.xml: error: file failed to compile.

**Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/Users/dominikerbsland/.gradle/caches/transforms-2/files-2.1/bac46a2a7f14666195dd82648a1252d5/res/values/values.xml:1167:5-1182:23: AAPT: error: duplicate value for resource 'attr/counterTextColor' with config ''.**

When I click on it I get to this line in a generated values.xml file:

```
<declare-styleable name="ThemeEnforcement">

    <attr format="boolean" name="enforceMaterialTheme"/>

    <attr format="boolean" name="enforceTextAppearance"/>

    <attr name="android:textAppearance"/>
```

Here with comments (removed them above for better reading):

```
<declare-styleable name="ThemeEnforcement">
 <!-- Internal flag used to denote that a style uses new attributes defined by
         Theme.MaterialComponents, and that the component should check via ThemeEnforcement that the
         client's app theme inherits from Theme.MaterialComponents. Not all usages of new attributes are problematic in the context of a legacy app theme. You
         should only use this flag if a particular usage is known to cause a visual glitch or crash.
         For example, tinting a vector drawable with a non-existent theme attribute is known to
         crash on pre-21 devices. -->
 <attr format="boolean" name="enforceMaterialTheme"/>
 <!-- Internal flag used to denote that a style requires that the textAppearance attribute is
         specified and evaluates to a valid text appearance. -->
 <attr format="boolean" name="enforceTextAppearance"/>
 <!-- Attribute used to check that a component has a TextAppearance specified on it. -->
 <attr name="android:textAppearance"/>
</declare-styleable>
```

So something with "ThemeEnforcement" must be in conflict with the library...

**Comment by HITGIF** [comment]
try 1.4.5

**Comment by taar1** [comment]
Great! It seems to run through now. Thanks!
