### ISSUE TITLE
android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.LayerDrawable

### ISSUE THREAD

**Issue by mcsong** [HITGIF/TextFieldBoxes#18]
Hello, 
I try to use this code in my xml code. 

    <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
        android:id="@+id/fg_save_as_file_container"

        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:labelText="@string/lbl_filename_without_ext"
        app:helperText="@string/lbl_filename_limit_desc"
        app:hasClearButton="true"
        app:minCharacters="2"
        app:maxCharacters="128"
        >

        <studio.carbonylgroup.textfieldboxes.ExtendedEditText
            android:id="@+id/fg_save_as_file_filename"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:maxLines="1"
            android:singleLine="true"
            android:text="" />

    </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>

And I got this error. 

FATAL EXCEPTION: main
                                                              Process: net.sjava.docs, PID: 8749
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{net.sjava.docs/net.sjava.docs.ui.activities.MainActivity}: android.view.InflateException: Binary XML file line #82: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.LayerDrawable
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                                  at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                               Caused by: android.view.InflateException: Binary XML file line #82: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.LayerDrawable
                                                               Caused by: java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.LayerDrawable
                                                                  at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.setPanelBackgroundColor(TextFieldBoxes.java:697)
                                                                  at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.onFinishInflate(TextFieldBoxes.java:285)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)

**Comment by mcsong** [comment]
Thank you so much. 
I will wait the next release.

**Comment by HITGIF** [comment]
**1.3.1 Release** now available 🎉🎉, check it out! :)

**Comment by mcsong** [comment]
Thank you so much.
