### ISSUE TITLE
FATAL EXCEPTION api level 15 UnsupportedOperationException

### ISSUE THREAD

**Issue by erdalceylan** [HITGIF/TextFieldBoxes#19]
FATAL EXCEPTION: main
java.lang.UnsupportedOperationException
at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:424)
at studio.carbonylgroup.textfieldboxes.ClipToBoundsView.onDraw(ClipToBoundsView.java:55)
at android.view.View.draw(View.java:11038)

**Comment by HITGIF** [comment]
Do you still have rounded corner after commenting that line?

**Comment by HITGIF** [comment]
fixed in release 1.3.2 :)
