### ISSUE TITLE
More crashing bugs.

### ISSUE THREAD

**Issue by mario** [HITGIF/TextFieldBoxes#68]
Sorry :D
![screen shot 2018-03-27 at 20 53 24](https://user-images.githubusercontent.com/5810/37988347-fb84d45c-3200-11e8-8909-0209b043654e.png)

**Comment by mario** [comment]
Any news on this maybe @HITGIF? :)

**Comment by mario** [comment]
Unfortunately, the error trace/crash doesn't show where exactly this happens and I use your text field in a few places. It does not crash on compile, and I can't reproduce but quite a few users on Android 7 and Android 8 have it.

**Comment by mario** [comment]
The line is basically this o.O

        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

**Comment by mario** [comment]
And it does NOT happen on Android 5 and 6.

**Comment by HITGIF** [comment]
Currently can't actually reproduce it without more information, sorry.

**Comment by mario** [comment]
In the mean time this happens to more and more users :(


> java.lang.IllegalStateException: 
>   at android.widget.RelativeLayout$DependencyGraph.getSortedViews (RelativeLayout.java:1786)
>   at android.widget.RelativeLayout.sortChildren (RelativeLayout.java:382)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:389)
>   at android.view.View.measure (View.java:23265)
>   at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:715)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:461)
>   at android.view.View.measure (View.java:23265)
>   at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:715)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:461)
>   at android.view.View.measure (View.java:23265)
>   at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:715)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:461)
>   at android.view.View.measure (View.java:23265)
>   at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:715)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:461)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
>   at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.onMeasure (TextFieldBoxes.java:357)
>   at android.view.View.measure (View.java:23265)
>   at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:715)
>   at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:461)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.support.design.widget.CoordinatorLayout.onMeasureChild (CoordinatorLayout.java:739)
>   at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild (HeaderScrollingViewBehavior.java:91)
>   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild (AppBarLayout.java:1361)
>   at android.support.design.widget.CoordinatorLayout.onMeasure (CoordinatorLayout.java:809)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
>   at android.support.v7.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:141)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1514)
>   at android.widget.LinearLayout.measureVertical (LinearLayout.java:806)
>   at android.widget.LinearLayout.onMeasure (LinearLayout.java:685)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1514)
>   at android.widget.LinearLayout.measureVertical (LinearLayout.java:806)
>   at android.widget.LinearLayout.onMeasure (LinearLayout.java:685)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6928)
>   at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
>   at com.android.internal.policy.DecorView.onMeasure (DecorView.java:898)
>   at android.view.View.measure (View.java:23265)
>   at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2873)
>   at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1910)
>   at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2165)
>   at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1779)
>   at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7810)
>   at android.view.Choreographer$CallbackRecord.run (Choreographer.java:911)
>   at android.view.Choreographer.doCallbacks (Choreographer.java:723)
>   at android.view.Choreographer.doFrame (Choreographer.java:658)
>   at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:897)
>   at android.os.Handler.handleCallback (Handler.java:789)
>   at android.os.Handler.dispatchMessage (Handler.java:98)
>   at android.os.Looper.loop (Looper.java:164)
>   at android.app.ActivityThread.main (ActivityThread.java:6938)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by mario** [comment]
java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout
       at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1909)
       at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:403)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:410)
       at android.view.View.measure(View.java:19149)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19149)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19149)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19149)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
       at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.onMeasure(TextFieldBoxes.java:357)
       at android.view.View.measure(View.java:19149)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2700)
       at android.view.View.measure(View.java:19149)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2481)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1440)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
       at android.view.ViewRootImpl.doTravers

**Comment by mario** [comment]
This happens in RTL environments.
